### ISSUE TITLE
Installation error: "octupus/scripts/run events.js:183, throw er; // unhandled 'error' event"

### ISSUE THREAD

**Issue by benjiebob** [PharmaLedger-IMI/epi-workspace#171]
I'm having an issue when trying to install epi-workspace. I'm running on a Ubuntu 18.04 Azure VM. 

Node version: v8.10.0
Npm version: 3.5.2
GCC version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Python version: Python 2.7.17
Node-Gyp version: v8.0.0
```
bjb10042@ginny:/scratch/bjb10042/code/epi-workspace$ npm install

> ePI-workspace@1.0.1 postinstall /scratch/bjb10042/code/epi-workspace
> node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run"

Running in STABLE (FREEZED) mode
Environment updated accordingly to env file passed as argument.
Preparing to execute cmd node ./node_modules/octopus/scripts/run
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ./node_modules/octopus/scripts/run ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm WARN ePI-workspace@1.0.1 scripts['server'] should probably be scripts['start'].
npm ERR! Linux 5.4.0-1046-azure
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ePI-workspace@1.0.1 postinstall: `node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ePI-workspace@1.0.1 postinstall script 'node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ePI-workspace package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ePI-workspace
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ePI-workspace
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /scratch/bjb10042/code/epi-workspace/npm-debug.log
```

I can also reproduce this issue when testing the [tutorial workspace](https://github.com/PrivateSky/tutorial-workspace/issues). My first thought was this issue might be caused if the target port 8080 is not open (or is used by another processed). I checked this is not the case with a simple 'hello world' nodejs app (based on [this](https://nodejs.org/en/docs/guides/getting-started-guide/)), which runs successfully:

```
const http = require('http');

const hostname = 'localhost';
const port = 8080;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

I'd be grateful if anyone could suggest a debugging strategy!

Thanks,
Ben

**Comment by benjiebob** [comment]
Apologies, I suddenly realise I’m apparently unable to follow instructions!

My node version was too old. Note that 

```sudo apt-get install nodejs```

on Ubuntu VM at the time of writing gives you a very old v8.10.0 which is far behind the required 12.14.0) as required. See the list of necessary dependencies (and note the versions!) [here](https://github.com/PrivateSky/tutorial-workspace#prerequisites).

Apologies!
Ben
