### ISSUE TITLE
npm i on fresh clone yield error

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#3]
Hello,
I am sharing the error output of running `npm i` on the fresh repo (run one hour ago). Just mentioning that it was working for me last Thursday/Friday.

- OS: `MacOS Mojave 10.14.6`
- Node: `v12.14.0`
- `brew info gcc`: `gcc: stable 10.2.0`
- `python --version`: `Python 2.7.16`

```
[Octopus] Running tasks for: [2] build privatesky
Running command: cd privatesky && npm run build

> PrivateSky@0.5.0 build /Users/podhrads/www/dsu/epi-workspace/privatesky
> node ./bin/scripts/pskbuild.js --projectMap=./builds/domain_build.json && node ./bin/scripts/pskbuild.js --projectMap=./builds/build.json

Found project map ./builds/domain_build.json
Reading targets and their dependencies list...
Starts rebuilding
Building target domain
domain done
Finished rebuilding
Found project map ./builds/build.json
Reading targets and their dependencies list...
Starts rebuilding
Building target webshims
Building target pskruntime
Building target pskWebServer
Building target consoleTools
Building target blockchain
Building target openDSU
Building target sandboxBase
Building target edfsBar
Building target testsRuntime
Building target csbBoot
Building target bindableModel
Building target swBoot
Building target hostBoot
Building target ssappBoot
Building target threadBoot
Building target domainBoot
Building target isolatesBoot
Building target launcherBoot
Building target walletBoot
pskruntime done
openDSU done
blockchain done
sandboxBase done
consoleTools done
edfsBar done
isolatesBoot done
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Can't walk dependency graph: Cannot find module 'swarm-engine/bootScripts/IsolateBootScript' from '/Users/podhrads/www/dsu/epi-workspace/privatesky/_fake.js'
    required by /Users/podhrads/www/dsu/epi-workspace/privatesky/_fake.js
    at /Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/resolve/lib/async.js:115:35
    at processDirs (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/resolve/lib/async.js:268:39)
    at isdir (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/resolve/lib/async.js:275:32)
    at /Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:158:21)
Emitted 'error' event on Readable instance at:
    at Labeled.<anonymous> (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/read-only-stream/index.js:28:44)
    at Labeled.emit (events.js:210:5)
    at Labeled.<anonymous> (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/stream-splicer/index.js:130:18)
    at Labeled.emit (events.js:210:5)
    at Deps.<anonymous> (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/stream-splicer/index.js:130:18)
    at Deps.emit (events.js:210:5)
    at /Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/module-deps/index.js:387:25
    at onresolve (/Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/module-deps/index.js:185:25)
    at /Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/browserify/index.js:528:22
    at /Users/podhrads/www/dsu/epi-workspace/privatesky/node_modules/browser-resolve/index.js:265:24 {
  code: 'MODULE_NOT_FOUND',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps] ],
    length: 1,
    label: 'deps'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! PrivateSky@0.5.0 build: `node ./bin/scripts/pskbuild.js --projectMap=./builds/domain_build.json && node ./bin/scripts/pskbuild.js --projectMap=./builds/build.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PrivateSky@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/podhrads/.npm/_logs/2020-11-02T17_15_55_119Z-debug.log
[Octopus] Running tasks for: [3] menu-wallet-prototype
Running command git clone --depth=1 --branch=master http://github.com/privatesky/menu-wallet-prototype.git "/Users/podhrads/www/dsu/epi-workspace/menu-wallet-prototype"
taskIndex: 3 actionIndex: 0 result: "Finished clone action on dependency menu-wallet-prototype"
Running command: cd menu-wallet-prototype && npm install

> menu-wallet@0.0.1 postinstall /Users/podhrads/www/dsu/epi-workspace/menu-wallet-prototype
> node ./node_modules/octopus/scripts/run

Looking for configuration file at path /Users/podhrads/www/dsu/epi-workspace/menu-wallet-prototype/octopus.json
[Octopus] Start checking dependencies...
[Octopus] Found 0 dependencies...
No [object Object] to process!
added 1 package and audited 1 package in 1.834s
found 0 vulnerabilities

[Octopus] Running tasks for: [4] leaflet-ssapp
Running command git clone --depth=1 --branch=master https://github.com/PharmaLedger-IMI/leaflet-ssapp.git "/Users/podhrads/www/dsu/epi-workspace/leaflet-ssapp"
taskIndex: 4 actionIndex: 0 result: "Finished clone action on dependency leaflet-ssapp"
Running command: cd leaflet-ssapp && npm install

> leaflet-ssapp@1.0.0 postinstall /Users/podhrads/www/dsu/epi-workspace/leaflet-ssapp
> node ./node_modules/octopus/scripts/run

Looking for configuration file at path /Users/podhrads/www/dsu/epi-workspace/leaflet-ssapp/octopus.json
[Octopus] Start checking dependencies...
[Octopus] Found 0 dependencies...
No [object Object] to process!
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN leaflet-ssapp@1.0.0 No description

added 1 package and audited 1 package in 2.289s
found 0 vulnerabilities

[Octopus] Running tasks for: [5] web-server/leaflet-wallet/loader
Running command git clone --depth=1 --branch=master http://github.com/privatesky/web-dossier-loader.git "/Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader"
taskIndex: 5 actionIndex: 0 result: "Finished clone action on dependency web-server/leaflet-wallet/loader"
Running command: cd web-server/leaflet-wallet/loader && npm install

> web-dossier-loader@0.2.0 preinstall /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader
> npx npm-force-resolutions

npx: installed 5 in 3.142s

> fsevents@1.2.13 install /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> web-dossier-loader@0.2.0 postinstall /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader
> node ./node_modules/octopus/scripts/run

Looking for configuration file at path /Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader/octopus.json
[Octopus] Start checking dependencies...
[Octopus] Found 1 dependencies...
[Octopus] Running tasks for: [0] PSK bundles
Start copying ../../../privatesky/psknode/bundles/swBoot.js to folder ./swBoot.js

/Users/podhrads/www/dsu/epi-workspace/web-server/leaflet-wallet/loader/node_modules/octopus/scripts/run.js:12
		throw err;
		^
Source directory or file "/Users/podhrads/www/dsu/epi-workspace/privatesky/psknode/bundles/swBoot.js" does not exists!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-dossier-loader@0.2.0 postinstall: `node ./node_modules/octopus/scripts/run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-dossier-loader@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/podhrads/.npm/_logs/2020-11-02T17_16_42_566Z-debug.log
Start copying web-server/leaflet-wallet/loader/loader-config.local.json-template to folder web-server/leaflet-wallet/loader/loader-config.local.json
[Octopus] Running tasks for: [6] themes/citrus-theme
Running command git clone --depth=1 --branch=master http://github.com/privatesky/citrus-theme.git "/Users/podhrads/www/dsu/epi-workspace/themes/citrus-theme"
taskIndex: 6 actionIndex: 0 result: "Finished clone action on dependency themes/citrus-theme"
Running command: cd themes/citrus-theme && npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN citrus-theme@1.0.0 No description
```

**Comment by salboaie** [comment]
Old and now invalid issue
