### ISSUE TITLE
Product page doesn't display success message after import

### ISSUE THREAD

**Issue by rite2bala** [PharmaLedger-IMI/epi-workspace#470]
![image](https://user-images.githubusercontent.com/44022980/145223669-658325f3-ade3-4860-9fda-b62964768f0e.png)

Steps to recreate the issue
--
1. Product - Import 
2. Select product file
3. press 'import' 
4. Action - view message"

**Comment by RakeshL-JnJ** [comment]
I am not sure but getting below exception in command line:
requestedPath: /pages/batches.html
Handling file: /pages/batches.html
Handling file: /pages/batches.html
127.0.0.1:8080 - [2021-12-13T10:09:52.354Z] GET:/anchor/vault/get-all-versions/7saRdSuZc8NvbcgiyPjV4uAKNpwNc4oGtfbnjPEgtPgtE5cxxjEbJKgvFk9xBbgQuoxR1vEDoU1SW7WSXx8J3 200 1.121ms
[STATUS 200][8.588 ms][GET] /pages/batches.html
3.91.87.65:8080 - [2021-12-13T10:09:52.350Z] GET:/iframe/65FmT6jYpmQXhAkCPpZszdAsN6PaXF5iDzidjA66N3Ld7JotSnqB4aqc8gSk4C4Pz3h1BxCX8XrL8wggffkmWW8VnRwG5SKB/pages/batches.html 200 8.86ms
3.91.87.65:8080 - [2021-12-13T10:09:53.019Z] GET:/anchor/vault/get-all-versions/7saRdSuZc8NvbcgiyPjV4tA6yqYVt3uyQMjBpEgodXtf23jCjQdBE64vMk1rQeZbEpomfLbGtejCYiSuwvRDq 200 1.277ms
3.91.87.65:8080 - [2021-12-13T10:09:53.366Z] GET:/anchor/vault/get-all-versions/7saRdSuZc8NvbcgiyPjV4mus1KmBYJaQfHkBziA4NmMZyUoMmuGTcnGuC1iVqTQuURSExSpFGEsMej3csFsBu 200 1.365ms
3.91.87.65:8080 - [2021-12-13T10:09:54.010Z] GET:/anchor/vault/get-all-versions/7saRdSuZc8NvbcgiyPjV4mus1KmBYJaQfHkBziA4NmMZyUoMmuGTcnGuC1iVqTQuURSExSpFGEsMej3csFsBu 200 1.374ms
requestedPath: /pages/import.translate.json
Handling file: /pages/import.translate.json
Handling file: /pages/import.translate.json
127.0.0.1:8080 - [2021-12-13T10:09:56.029Z] GET:/anchor/vault/get-all-versions/7saRdSuZc8NvbcgiyPjV4uAKNpwNc4oGtfbnjPEgtPgtE5cxxjEbJKgvFk9xBbgQuoxR1vEDoU1SW7WSXx8J3 200 1.098ms
Error reading file /code/pages/import.translate.json Error: Path </pages/import.translate.json> not found.
    at ErrorWrapper (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:17888:22)
    at createOpenDSUErrorWrapper (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:17915:12)
    at _readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:661:50)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1194:17
    at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)
    at Archive.readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1183:9)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1202:36
    at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7116:25
    at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32
    at Object.Manifest.manifestHandler.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7122:9)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1802:25
    at getManifest (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1114:20)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1792:13
    at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)
    at Archive.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1789:9)
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7111:36
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7166:13
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:21195:24
    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:570:24
    at executeForSingleEntry (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:22615:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  originalMessage: 'Path </pages/import.translate.json> not found.',
  previousError: Error: Path </pages/import.translate.json> not found.
      at BrickMap.getBricksMeta (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:4587:19)
      at Object.apply (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:3281:50)
      at _readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:659:45)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1194:17
      at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)
      at Archive.readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1183:9)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1202:36
      at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7116:25
      at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32
      at Object.Manifest.manifestHandler.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7122:9)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1802:25
      at getManifest (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1114:20)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1792:13
      at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)
      at Archive.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1789:9)
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7111:36
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7166:13
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:21195:24
      at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:570:24
      at executeForSingleEntry (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:22615:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  debug_message: 'Failed to find any info for path /pages/import.translate.json in brickmap',
  debug_stack: 'Error: Path </pages/import.translate.json> not found.\n' +
    '    at BrickMap.getBricksMeta (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:4587:19)\n' +
    '    at Object.apply (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:3281:50)\n' +
    '    at _readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:659:45)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1194:17\n' +
    '    at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)\n' +
    '    at Archive.readFile (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1183:9)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1202:36\n' +
    '    at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7116:25\n' +
    '    at newFn (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:35325:20)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1809:32\n' +
    '    at Object.Manifest.manifestHandler.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7122:9)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1802:25\n' +
    '    at getManifest (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1114:20)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1792:13\n' +
    '    at waitIfDSUIsRefreshing (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:424:20)\n' +
    '    at Archive.getArchiveForPath (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:1789:9)\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7111:36\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:7166:13\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:21195:24\n' +
    '    at /home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:570:24\n' +
    '    at executeForSingleEntry (/home/ubuntu/ePI/PL_Sourcebase/03Dec21/epi-workspace/privatesky/psknode/bundles/nodeBoot.js:22615:13)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
}
[STATUS 500][9.479 ms][GET] /pages/import.translate.json

**Comment by adiganga2002** [comment]
Fixed with latest codebase.
