### ISSUE TITLE
epi-workspace running DSUs from the command line Failed to load module  ../privatesky/psknode/bundles/openDSU  with error: TypeError: Cannot redefine property: environmentType

### ISSUE THREAD

**Issue by jpluis** [PharmaLedger-IMI/epi-workspace#7]
This issue is important so that we can check the behaviour of some openDSU APIs from the command line without having to modify/run web applications.

This issue also happened on the tutorial-workspace, but as it is unstable (from issue #6) I tryed it on epi-workspace, with the same problem.

Copying the https://github.com/PrivateSky/tutorial-workspace/tree/main/helloworld-dsu on to the epi-workspace (and having the epi-workspace running, and with a previous npm run build-all),

```
jpsl@PDM-00781:~/develop/PharmaLedger/epi-workspace/helloworld-dsu$ node main.js 
Logger not available, using console
Fix the fixMe to not display on console but put in logs
Redefining require for node
Failed to load module  ../privatesky/psknode/bundles/openDSU  with error: TypeError: Cannot redefine property: environmentType
    at Function.defineProperty (<anonymous>)
    at Object.enableForEnvironment (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/openDSU.js:17760:12)
    at Object.openDSURequire./export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/builds/tmp/openDSU.js../openDSU_intermediar (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/openDSU.js:3:4)
    at o (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/openDSU.js:1:280)
    at r (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/openDSU.js:1:446)
    at Object.<anonymous> (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/openDSU.js:1:475)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at originalRequire (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18826:49)
    at tryRequireSequence (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18707:26)
    at Module.newLoader [as require] (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18847:20)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/export/home/jpsl/develop/PharmaLedger/epi-workspace/helloworld-dsu/main.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
double-check has intercepted an uncaught exception
Error: Failed to load module ../privatesky/psknode/bundles/openDSU
Stack:
    at tryRequireSequence (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18730:19)
    at Module.newLoader [as require] (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18847:20)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/export/home/jpsl/develop/PharmaLedger/epi-workspace/helloworld-dsu/main.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Test should fail because: Uncaught Exception! Error: Failed to load module ../privatesky/psknode/bundles/openDSU
    at tryRequireSequence (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18730:19)
    at Module.newLoader [as require] (/export/home/jpsl/develop/PharmaLedger/epi-workspace/privatesky/psknode/bundles/testsRuntime.js:18847:20)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/export/home/jpsl/develop/PharmaLedger/epi-workspace/helloworld-dsu/main.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
asset.begin was not called, the exit time for the test is automatically set to 2 seconds. asset.callback can increase this time
```

**Comment by alexgheorghiu** [comment]
tutorial-workspace at 6ab7bf35309ee279dc941dc247915f1348b2edd5 is free of this bug.

**Comment by jpluis** [comment]
I confirm that the tutorial-workspace is working again, and helloworld-dsu (from the tutorial-workspace) is working again inside both the tutorial-workspace and epi-workspace.
Thank you. (We can proceed with our preliminary OpenDSU API exploration).
