### ISSUE TITLE
Investigate error handling on Update product

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#939]
Got:
iframeBoot.js:44206 Uncaught (in promise) Error: Failed to update record with key 1664791018487 in table logs (Anchoring conflict error)
    at ErrorWrapper (iframeBoot.js:44206:22)
    at createOpenDSUErrorWrapper (iframeBoot.js:44236:12)
    at iframeBoot.js:38908:37
    at iframeBoot.js:40171:55
    at iframeBoot.js:10799:57
    at endAnchoring (iframeBoot.js:12333:9)
    at iframeBoot.js:12986:28
    at LatestVersionStrategy.mergeConflictsHandled (iframeBoot.js:14269:9)
    at iframeBoot.js:14910:26
    at State.prepareNewChangesForAnchoring (iframeBoot.js:12069:20)

Not able to commit batch Error: Anchoring conflict error
    at ErrorWrapper (iframeBoot.js:44209:22)
    at createOpenDSUErrorWrapper (iframeBoot.js:44236:12)
    at iframeBoot.js:10799:58
    at endAnchoring (iframeBoot.js:12333:9)
    at iframeBoot.js:12986:28
    at LatestVersionStrategy.mergeConflictsHandled (iframeBoot.js:14269:9)
    at iframeBoot.js:14910:26
    at State.prepareNewChangesForAnchoring (iframeBoot.js:12069:20)
    at iframeBoot.js:14905:19
    at iframeBoot.js:12097:13

But the modal screen remains on screen

**Comment by salboaie** [comment]
Sub task1: Change the PK of the audit log records to be  hash(concat(GTIN,BATCH,VCH))  where VCH is the number of entries in the anchor  of the product or of the batch
Sub task2: check and remove any attempt to update a log entry   (only inserts are allowed)
